'use client';
import {useState,useMemo,useRef,useEffect,useCallback} from 'react';
import {MapPin,Search,Layers,Plus,Minus,LocateFixed,Route as RouteIcon,ArrowRight,ArrowLeft,ArrowUpDown,X,ChevronUp,ChevronDown,DoorOpen,Building2,Info,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {simplifyRoute} from '@/lib/route-smoothing';
import plan,{rooms,roomById,findRoute,matches,type Room,type TravelMode,type MapRoute} from '@/lib/navigation';
function Stairs({size=20}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M3 20h5v-5h5v-5h5V5h3M4 10l7-7M4 3h7v7"/></svg>}
function Elevator({size=20}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="4" y="8" width="16" height="13" rx="2"/><path d="M12 8v13M6 5l3-3 3 3m2-3 3 3 3-3"/></svg>}
const listedRooms=rooms.filter(r=>r.kind!=='unknown');
function RoomPicker({value,onChange,label}:{value:string;onChange:(id:string)=>void;label:string}){
 return <Combobox items={listedRooms} value={roomById.get(value)||null} onValueChange={v=>onChange(v?.id||'')} itemToStringLabel={(r:Room)=>r.label} isItemEqualToValue={(a:Room,b:Room)=>a.id===b.id} filter={(item:Room,query:string)=>matches(item,query)}>
 <ComboboxInput aria-label={label} placeholder="Číslo místnosti nebo vchod" className="room-picker" showClear/>
 <ComboboxContent className="picker-popup"><ComboboxEmpty>Žádná místnost nenalezena.</ComboboxEmpty><ComboboxList>{(r:Room)=><ComboboxItem value={r} key={r.id}><span>{r.label}</span><small>{r.floor+1}. NP</small></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox>;
}
function nextFloorText(floor:number){return floor===0?'Pokračuj do přízemí':`Pokračuj do ${floor}. patra`;}
function mapLabel(r:Room){if(r.label.startsWith('Šatny')||r.kind==='unknown'||r.id.includes('unclear'))return '';if(r.kind==='wc')return 'WC';return r.code|| (r.label.startsWith('Menza')?'Menza':r.label);}
export default function Home(){
 const [floor,setFloor]=useState(0),[query,setQuery]=useState(''),[selected,setSelected]=useState<string>(''),[tab,setTab]=useState('rooms');
 const [from,setFrom]=useState('entry-main'),[to,setTo]=useState(''),[mode,setMode]=useState<TravelMode>('stairs'),[route,setRoute]=useState<MapRoute|null>(null),[error,setError]=useState(''),[expanded,setExpanded]=useState(false),[info,setInfo]=useState(false);
 const [minimized,setMinimized]=useState(true);
 const sheetGesture=useRef<{id:number;startY:number;startLevel:number;moved:boolean}|null>(null);
 const sheetLevel=minimized?0:expanded?2:1;
 function setSheetLevel(level:number){setMinimized(level===0);setExpanded(level===2);if(level===0&&(document.activeElement instanceof HTMLElement))document.activeElement.blur();}
 function sheetDown(e:React.PointerEvent<HTMLButtonElement>){if(e.pointerType==='mouse'&&e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);sheetGesture.current={id:e.pointerId,startY:e.clientY,startLevel:sheetLevel,moved:false};}
 function sheetMove(e:React.PointerEvent<HTMLButtonElement>){const g=sheetGesture.current;if(g&&g.id===e.pointerId&&Math.abs(e.clientY-g.startY)>10)g.moved=true;}
 function sheetUp(e:React.PointerEvent<HTMLButtonElement>){const g=sheetGesture.current;if(!g||g.id!==e.pointerId)return;const delta=e.clientY-g.startY;if(e.type!=='pointercancel'&&g.moved&&Math.abs(delta)>28)setSheetLevel(Math.max(0,Math.min(2,g.startLevel+(delta<0?1:-1))));}
 function openSheet(nextTab:string){setTab(nextTab);setMinimized(false);setExpanded(nextTab==='rooms'||!!route);requestAnimationFrame(()=>{if(nextTab==='rooms')document.querySelector<HTMLInputElement>('.search-box input')?.focus();});}
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[mapSize,setMapSize]=useState({width:0,height:0});
 const svgRef=useRef<SVGSVGElement>(null),gesture=useRef({points:new Map<number,{x:number;y:number}>(),last:{x:0,y:0,d:0},start:{x:0,y:0},moved:false,targetRoom:'',targetTransfer:null as number|null});
 const selectedRoom=roomById.get(selected), f=plan.floors[floor];
 const filtered=useMemo(()=>listedRooms.filter(r=>query?matches(r,query):r.floor===floor).sort((a,b)=>a.label.localeCompare(b.label,'cs',{numeric:true})),[query,floor]);
 const fit=useCallback(()=>{setZoom(1);setPan({x:0,y:0});},[]);
 const changeFloor=useCallback((n:number)=>{setFloor(n);fit();},[fit]);
 const selectRoom=useCallback((r:Room)=>{setMinimized(false);setSelected(r.id);setTo(r.id);setRoute(null);setError('');changeFloor(r.floor);setExpanded(false);},[changeFloor]);
 const clearRoute=()=>{setRoute(null);setError('');};
 const calculate=useCallback((a=from,b=to,m=mode)=>{try{const result=findRoute(a,b,m);setRoute(result);setError('');setSelected(b);changeFloor(result.from.floor);setExpanded(false);setMinimized(true);return result;}catch(e){setError(e instanceof Error?e.message:'Trasu se nepodařilo vypočítat.');setRoute(null);return null;}},[from,to,mode,changeFloor]);
 const parts=useMemo(()=>route?.parts.filter(p=>p.floor===floor).map(p=>({...p,points:simplifyRoute(p.points,p.floor)}))||[],[route,floor]);
 const partIndex=route?.parts.findIndex(p=>p.floor===floor)??-1;
 const base=floor===0?[f.viewBox[0],f.viewBox[1],f.viewBox[2],960]:f.viewBox;
 const vb=[base[0]+base[2]*(1-1/zoom)/2+pan.x,base[1]+base[3]*(1-1/zoom)/2+pan.y,base[2]/zoom,base[3]/zoom];
 const mapScale=mapSize.width&&mapSize.height?Math.min(mapSize.width/vb[2],mapSize.height/vb[3]):.5;
 const connectorMarkers=useMemo(()=>{
  const groups:{id:string;kind:string;name:string;point:number[];nodes:number[];active:boolean;nextFloor:number|null;offset:number[]}[]=[];
  for(const c of plan.connectors.filter(c=>c.floor===floor)){
   const nearby=groups.find(g=>g.kind===c.kind&&Math.hypot(g.point[0]-c.point[0],g.point[1]-c.point[1])*mapScale<28);
   if(nearby){nearby.point=[(nearby.point[0]+c.point[0])/2,(nearby.point[1]+c.point[1])/2];nearby.nodes.push(c.node);}else groups.push({id:c.id,kind:c.kind,name:c.kind==='stairs'?'Schody':'Výtah',point:[...c.point],nodes:[c.node],active:false,nextFloor:null,offset:[0,0]});
  }
  const part=parts[0];if(part?.transition){const end=part.points.at(-1)!;const nearest=groups.filter(c=>c.kind===part.transition!.kind).sort((a,b)=>Math.hypot(a.point[0]-end[0],a.point[1]-end[1])-Math.hypot(b.point[0]-end[0],b.point[1]-end[1]))[0];if(nearest){nearest.active=true;nearest.nextFloor=part.transition.floor;}}
  for(const c of groups)if(floor===0&&Math.hypot(c.point[0]-742.79,c.point[1]-752.73)*mapScale<35)c.offset[0]=-14;
  const wcPoints=rooms.filter(r=>r.floor===floor&&r.kind==='wc').map(r=>r.point);
  for(let pass=0;pass<12;pass++){for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++){const a=groups[i],b=groups[j],dx=(b.point[0]-a.point[0])*mapScale+b.offset[0]-a.offset[0],dy=(b.point[1]-a.point[1])*mapScale+b.offset[1]-a.offset[1],d=Math.hypot(dx,dy);if(d<30){const shift=(30-d)/2+.1,ux=d?dx/d:1,uy=d?dy/d:0;a.offset[0]-=ux*shift;a.offset[1]-=uy*shift;b.offset[0]+=ux*shift;b.offset[1]+=uy*shift;}}
   for(const c of groups)for(const p of wcPoints){const dx=(c.point[0]-p[0])*mapScale+c.offset[0],dy=(c.point[1]-p[1])*mapScale+c.offset[1],d=Math.hypot(dx,dy);if(d<26){const shift=26-d;c.offset[0]+=(d?dx/d:-1)*shift;c.offset[1]+=(d?dy/d:0)*shift;}}
  }
  return groups;
 },[floor,mapScale,parts]);
 const entry=roomById.get('entry-main')!;
 const visibleBounds=[vb[0]-(mapSize.width/mapScale-vb[2])/2,vb[1]-(mapSize.height/mapScale-vb[3])/2,mapSize.width/mapScale,mapSize.height/mapScale];
 const entryOutside=floor===0&&(entry.point[0]<visibleBounds[0]+65/mapScale||entry.point[0]>visibleBounds[0]+visibleBounds[2]-65/mapScale||entry.point[1]<visibleBounds[1]+10/mapScale||entry.point[1]>visibleBounds[1]+visibleBounds[3]-66/mapScale);
 const wcMarkers=useMemo(()=>{
  const groups=new Map<string,Room[]>();for(const r of rooms.filter(r=>r.floor===floor&&r.kind==='wc')){const key=r.id.split('-').slice(0,3).join('-');groups.set(key,[...(groups.get(key)||[]),r]);}
  return [...groups.entries()].flatMap(([id,rs])=>{if(rs.length===2&&Math.hypot(rs[0].point[0]-rs[1].point[0],rs[0].point[1]-rs[1].point[1])*mapScale<24)return [{id,point:[(rs[0].point[0]+rs[1].point[0])/2,(rs[0].point[1]+rs[1].point[1])/2]}];return rs.map(r=>({id:r.id,point:r.point}));});
 },[floor,mapScale]);
 const labelLayouts=useMemo(()=>{
  const result=new Map<string,{labels:string[];fontSize:number;rotate:boolean}>(),occupied:{x:number;y:number;w:number;h:number}[]=[...wcMarkers.map(m=>({x:m.point[0],y:m.point[1],w:19/mapScale,h:12/mapScale})),...connectorMarkers.flatMap(m=>[{x:m.point[0]+m.offset[0]/mapScale,y:m.point[1]+m.offset[1]/mapScale,w:30/mapScale,h:30/mapScale},...(m.active?[{x:m.point[0],y:m.point[1]-44/mapScale,w:155/mapScale,h:44/mapScale}]:[])])];
  const ordered=[...f.spaces].sort((a,b)=>Number(b.roomIds.includes(selected))-Number(a.roomIds.includes(selected))||(b.bounds[2]-b.bounds[0])*(b.bounds[3]-b.bounds[1])-(a.bounds[2]-a.bounds[0])*(a.bounds[3]-a.bounds[1]));
  for(const space of ordered){
   if(space.kind==='wc')continue;
   const labels=(space.kind==='wc'?space.roomIds.filter(id=>roomById.get(id)?.kind==='wc'):space.roomIds).map(id=>roomById.get(id)).filter((r):r is Room=>!!r).map(mapLabel).filter((v,i,a)=>!!v&&a.indexOf(v)===i);if(!labels.length)continue;
   const w=space.bounds[2]-space.bounds[0],h=space.bounds[3]-space.bounds[1],rotate=w<55&&h>w&&labels.every(l=>l.startsWith('U'));
   const longest=Math.max(...labels.map(l=>l.length)),availableWidth=((rotate?h:w)-(space.kind==='wc'?1:9))*mapScale,availableHeight=((rotate?w:h)-(space.kind==='wc'?1:8))*mapScale;
   const pixels=Math.min(10,availableWidth/(longest*.6),availableHeight/(labels.length*1.25));
   if(pixels<(space.kind==='wc'?6.5:7.5))continue;
   const fontSize=pixels/mapScale,tw=longest*fontSize*.6,th=labels.length*fontSize*1.25;
   const labelPoint=space.kind==='wc'?(roomById.get(space.roomIds[0])?.point||space.center):space.center;const box={x:labelPoint[0],y:labelPoint[1],w:rotate?th:tw,h:rotate?tw:th};
   if(occupied.some(b=>Math.abs(box.x-b.x)<(box.w+b.w)/2+(space.kind==='wc'?.8:3)/mapScale&&Math.abs(box.y-b.y)<(box.h+b.h)/2+2/mapScale))continue;
   occupied.push(box);result.set(space.id,{labels,fontSize,rotate});
  }
  return result;
 },[f,mapScale,selected,wcMarkers,connectorMarkers]);
 useEffect(()=>{const el=svgRef.current;if(!el)return;const observer=new ResizeObserver(()=>{const rect=el.getBoundingClientRect();setMapSize({width:rect.width,height:rect.height});});observer.observe(el);return()=>observer.disconnect();},[]);
 const changeZoom=(next:number)=>{const clamped=Math.min(5,Math.max(1,next));setZoom(clamped);if(clamped===1)setPan({x:0,y:0});};
 function pointerDown(e:React.PointerEvent<SVGSVGElement>){if(e.button!==0&&e.pointerType==='mouse')return;const g=gesture.current;e.currentTarget.setPointerCapture(e.pointerId);if(g.points.size===0){g.start={x:e.clientX,y:e.clientY};g.moved=false;g.targetRoom=(e.target as Element).closest('[data-room-id]')?.getAttribute('data-room-id')||'';const transfer=(e.target as Element).closest('[data-transfer-floor]')?.getAttribute('data-transfer-floor');g.targetTransfer=transfer==null?null:Number(transfer);}else{g.moved=true;}g.points.set(e.pointerId,{x:e.clientX,y:e.clientY});updateGesture();}
 function updateGesture(){const ps=[...gesture.current.points.values()];if(!ps.length)return;gesture.current.last={x:ps.reduce((a,p)=>a+p.x,0)/ps.length,y:ps.reduce((a,p)=>a+p.y,0)/ps.length,d:ps.length>1?Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y):0};}
 function pointerMove(e:React.PointerEvent<SVGSVGElement>){const g=gesture.current;if(!g.points.has(e.pointerId))return;g.points.set(e.pointerId,{x:e.clientX,y:e.clientY});const last=g.last;updateGesture();const now=g.last,rect=e.currentTarget.getBoundingClientRect(),scale=Math.max(vb[2]/rect.width,vb[3]/rect.height);if(Math.hypot(e.clientX-g.start.x,e.clientY-g.start.y)>5)g.moved=true;setPan(p=>({x:Math.max(-base[2],Math.min(base[2],p.x-(now.x-last.x)*scale)),y:Math.max(-base[3],Math.min(base[3],p.y-(now.y-last.y)*scale))}));if(g.points.size>1&&last.d>0){setZoom(z=>Math.min(5,Math.max(1,z*now.d/last.d)));g.moved=true;}}
 function pointerUp(e:React.PointerEvent<SVGSVGElement>){gesture.current.points.delete(e.pointerId);if(e.type!=='pointercancel'&&!gesture.current.moved&&gesture.current.points.size===0){const r=roomById.get(gesture.current.targetRoom);if(r)selectRoom(r);else if(gesture.current.targetTransfer!==null)changeFloor(gesture.current.targetTransfer);}updateGesture();}
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setInfo(false);setSelected('');setExpanded(false);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'show_fai_room',description:'Find a room by its exact room identifier and display it on its floor.',inputSchema:{type:'object',properties:{roomId:{type:'string'}},required:['roomId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const id=(input as {roomId?:string})?.roomId;const r=id&&roomById.get(id);if(!r||r.kind==='unknown')throw new Error('Unknown room identifier');selectRoom(r);return new Promise(resolve=>requestAnimationFrame(()=>resolve({id:r.id,label:r.label,floor:r.floor+1})));}});
  register({name:'plan_fai_route',description:'Calculate and show an indoor route between an entrance or room and another room, using stairs or an elevator.',inputSchema:{type:'object',properties:{from:{type:'string'},to:{type:'string'},mode:{type:'string',enum:['stairs','elevator']}},required:['from','to','mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=input as {from:string;to:string;mode:TravelMode};if(!listedRooms.some(r=>r.id===x.from)||!listedRooms.some(r=>r.id===x.to))throw new Error('Unknown room identifier');const r=findRoute(x.from,x.to,x.mode);setFrom(x.from);setTo(x.to);setMode(x.mode);setTab('route');setRoute(r);setSelected(x.to);changeFloor(r.from.floor);return new Promise(resolve=>requestAnimationFrame(()=>resolve({from:r.from.label,to:r.to.label,floors:r.parts.map(p=>p.floor+1),mode:r.mode})));}});
  return()=>lifecycle.abort();
 },[selectRoom,changeFloor]);
 return <main className="app"><header className="topbar"><a className="official-brand" href="https://www.utb.cz/" target="_blank" rel="noreferrer" aria-label="Univerzita Tomáše Bati ve Zlíně, Fakulta aplikované informatiky"><img src={(process.env.NEXT_PUBLIC_BASE_PATH||'')+'/fai-logo.gif'} alt="Univerzita Tomáše Bati ve Zlíně – Fakulta aplikované informatiky"/></a><span className="app-title">Mapa <b>U5</b></span><span className="address"><MapPin size={16}/> Nad Stráněmi 4511, Zlín</span><button className="info-button" aria-label="O mapě" onClick={()=>setInfo(!info)}><Info size={20}/></button></header>
 <div className="workspace">
 <aside className={'panel '+(expanded?'expanded ':'')+(minimized?'minimized':'')} aria-label="Vyhledávání a navigace">
 <div className="sheet-controls"><button className="sheet-handle" onPointerDown={sheetDown} onPointerMove={sheetMove} onPointerUp={sheetUp} onPointerCancel={e=>{if(sheetGesture.current)sheetGesture.current.moved=true;}} onClick={()=>{if(sheetGesture.current?.moved){sheetGesture.current=null;return;}setSheetLevel(minimized?1:sheetLevel-1);}} aria-label={minimized?'Otevřít panel':expanded?'Zmenšit panel':'Sbalit panel dolů'} aria-expanded={!minimized}><span/>{minimized?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>{!minimized&&<button className="sheet-expand" aria-label={expanded?'Zmenšit seznam':'Rozbalit seznam místností'} onClick={()=>setSheetLevel(expanded?1:2)}>{expanded?<ChevronDown size={18}/>:<ChevronUp size={18}/>}</button>}</div>
 <div className="sheet-peek"><button onClick={()=>openSheet('rooms')}><Search size={19}/><span>Hledat místnost</span></button><button onClick={()=>openSheet('route')}><RouteIcon size={19}/><span>{route?'Upravit trasu':'Navigace'}</span></button></div>
 <div className="panel-intro"><span className="eyebrow">FAKULTA APLIKOVANÉ INFORMATIKY</span><h1>Najdi svou<br/><span>cestu.</span></h1><p>Tvoje fakulta. Přehledně a na dosah.</p></div>
 <Tabs value={tab} onValueChange={v=>{setTab(String(v));setError('');}} className="journey-tabs"><TabsList><TabsTrigger value="rooms"><Search size={17}/> Místnosti</TabsTrigger><TabsTrigger value="route"><RouteIcon size={17}/> Navigace</TabsTrigger></TabsList></Tabs>
 {tab==='rooms'?<><div className="search-box"><Search size={20}/><input aria-label="Hledat místnost ve všech podlažích" placeholder="Hledat místnost, např. U54/212" value={query} onChange={e=>{setQuery(e.target.value);setSelected('');setMinimized(false);setExpanded(true);}}/>{query&&<button aria-label="Vymazat hledání" onClick={()=>setQuery('')}><X size={17}/></button>}</div>
 {selectedRoom&&<div className="room-detail"><div className="detail-top"><span className="room-tag">{selectedRoom.kind==='entrance'?<DoorOpen size={18}/>:<MapPin size={18}/>}</span><div><h2>{selectedRoom.label}</h2><p>{selectedRoom.floor+1}. podlaží · {plan.floors[selectedRoom.floor].name}</p></div><button className="plain-button" aria-label="Zavřít detail místnosti" onClick={()=>setSelected('')}><X size={18}/></button></div><div className="detail-actions"><button className="secondary-button" onClick={()=>{setFrom(selectedRoom.id);setTo('');clearRoute();setTab('route');}}>Odtud</button><button className="primary-button" onClick={()=>{setTo(selectedRoom.id);setTab('route');calculate(from,selectedRoom.id,mode);}}>Navigovat sem <ArrowRight size={17}/></button></div></div>}
 <div className="section-heading"><h2>{query?'Výsledky ve všech podlažích':f.subtitle+' · místnosti'}</h2><span>{filtered.length}</span></div><div className="room-list">{filtered.length===0?<div className="empty-state"><Search size={24}/><h3>Místnost jsme nenašli</h3><p>Zkus celé číslo (U54/212), část čísla nebo „vchod“.</p></div>:filtered.map(r=><button className={'room-row '+(selected===r.id?'selected':'')} onClick={()=>selectRoom(r)} key={r.id}><span className={'room-icon '+r.kind}>{r.kind==='entrance'?<DoorOpen size={19}/>:<Building2 size={18}/>}</span><span><strong>{r.label}</strong><small>{r.floor+1}. podlaží{r.name&&r.code?' · '+r.name:''}</small></span><ArrowRight size={16}/></button>)}</div>
 </>:<div className="routing-panel">{route&&<div className="route-compact"><div><strong>{route.from.label} <ArrowRight size={13}/> {route.to.label}</strong><small>{route.mode==='stairs'?'Po schodech':'Výtahem'} · {route.parts.length===1?'stejné podlaží':route.parts.length+' podlaží'}</small></div><button className="secondary-button" aria-label="Upravit trasu" onClick={()=>setExpanded(true)}>Upravit</button></div>}<div className="route-fields"><div className="route-field"><span className="waypoint from">A</span><div><label>Odkud</label><RoomPicker value={from} label="Začátek trasy" onChange={v=>{setFrom(v);clearRoute();}}/></div></div><button className="swap-button" aria-label="Prohodit začátek a cíl" onClick={()=>{setFrom(to);setTo(from);clearRoute();}}><ArrowUpDown size={18}/></button><div className="route-field"><span className="waypoint to">B</span><div><label>Kam</label><RoomPicker value={to} label="Cíl trasy" onChange={v=>{setTo(v);clearRoute();}}/></div></div></div>
 <Tabs value={mode} onValueChange={v=>{setMode(v as TravelMode);clearRoute();}} className="travel-mode"><TabsList><TabsTrigger value="stairs"><Stairs size={17}/> Po schodech</TabsTrigger><TabsTrigger value="elevator"><Elevator size={17}/> Výtahem</TabsTrigger></TabsList></Tabs>
 <button className="primary-button route-submit" disabled={!from||!to} onClick={()=>calculate()}><RouteIcon size={19}/> Zobrazit trasu</button>{error&&<p role="alert" className="route-error">{error}</p>}
 {route&&<div className="route-result" aria-live="polite"><div className="route-summary"><Check size={18}/><strong>{route.from.id===route.to.id?'Už jsi v cíli':route.transfers===0?'Trasa v jednom podlaží':route.parts.length+' podlaží · '+(route.mode==='stairs'?'po schodech':'výtahem')}</strong><button className="plain-button" onClick={()=>setRoute(null)} aria-label="Zrušit trasu"><X size={17}/></button></div>
 <ol className="route-steps">{route.parts.map((p,i)=><li key={i} className={p.floor===floor?'current':''}><button onClick={()=>changeFloor(p.floor)}><span className="step-number">{i+1}</span><span><strong>{p.floor+1}. podlaží · {plan.floors[p.floor].name}</strong><small>{i===0?'Od '+route.from.label:i===route.parts.length-1?'K místnosti '+route.to.label:'Pokračuj přes podlaží'}</small>{p.transition&&<span className="transition-text">{p.transition.kind==='stairs'?<Stairs size={14}/>:<Elevator size={14}/>} {p.transition.name} → {p.transition.floor+1}. NP</span>}</span>{p.floor===floor&&<span className="here-dot"/>}</button></li>)}</ol>


 </div>}
 {!route&&<p className="routing-note"><Info size={15}/> Začni u vchodu nebo vyber libovolnou místnost.</p>}
 </div>}
 <div className="panel-bottom"><span className="yellow-dot"/><p>Fakulta aplikované informatiky · U5</p></div>
 </aside>
 <section className="map-area" aria-label="Interaktivní mapa FAI">
 <div className="map-caption"><span className="live-dot"/> BUDOVA U5 <span>/</span> {f.subtitle}</div>
 <Tabs className="floor-switch" value={floor} onValueChange={v=>changeFloor(Number(v))}><span className="eyebrow"><Layers size={15}/> PODLAŽÍ</span><TabsList>{[0,1,2].map(n=><TabsTrigger key={n} value={n} aria-label={`${n+1}. podlaží – ${plan.floors[n].name}`}><b>{n+1}. NP</b><span>{plan.floors[n].name}</span>{route?.parts.some(p=>p.floor===n)&&<i className="floor-route-dot"/>}</TabsTrigger>)}</TabsList></Tabs>
 <div className="map-interaction-hint">Posuň mapu · přibliž prsty</div>
 <svg ref={svgRef} className={'floor-map '+(route?'navigating':'')} viewBox={vb.join(' ')} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onWheel={e=>{changeZoom(zoom*(e.deltaY<0?1.15:1/1.15));}} role="group" aria-label={f.subtitle+' – kliknutím vyber místnost'}>
 <defs><pattern id="outside-hatch" width="12" height="12" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="12" height="12" fill="#e0e8dd"/><path d="M0 0V12" stroke="#c5d1bd" strokeWidth="1"/></pattern><filter id="pin-shadow"><feDropShadow dx="0" dy="2" stdDeviation="2" floodOpacity=".18"/></filter></defs>
 {floor===0&&<g className="parking-context" aria-label="Parkoviště před budovou"><rect x="322" y="790" width="390" height="122" rx="12"/><path d="M338 808v25h36v-25m9 0v25h36v-25m9 0v25h36v-25m9 0v25h36v-25m9 0v25h36v-25M338 894v-25h36v25m9 0v-25h36v25m9 0v-25h36v25"/><g transform={`translate(463 852) scale(${1/mapScale})`}><rect className="parking-sign" x="-51" y="-8" width="16" height="16" rx="3"/><text className="parking-letter" x="-43" y=".5">P</text><text className="parking-name" x="-29" y=".5">Parkoviště</text></g></g>}
 <path d={f.outline} className="building-depth" fillRule="evenodd" transform="translate(0 5)"/>
 <path d={f.outline} className="building-floor" fillRule="evenodd"/>
 {f.spaces.map(space=>{const assigned=space.roomIds.map(id=>roomById.get(id)!).filter(r=>!!r&&r.kind!=='unknown'),r=assigned.find(r=>r.id===selected)||assigned[0],active=assigned.some(r=>r.id===selected),layout=labelLayouts.get(space.id);const [x,y]=space.kind==='wc'?(assigned.find(r=>r.kind==='wc')?.point||space.center):space.center;return <g key={space.id} data-room-id={r?.id} className={'map-room '+(active?'is-selected ':'')+(assigned.some(r=>r.id===route?.from.id||r.id===route?.to.id)?'route-endpoint':'')}><path d={space.path} fillRule="evenodd" className={'room-hit '+space.kind+(active?' active':'')} role={r?'button':undefined} tabIndex={r?0:undefined} aria-label={r?assigned.map(r=>r.label).join(', '):undefined} onKeyDown={e=>{if(r&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectRoom(r);}}}/>{space.kind==='outdoor'&&mapScale>.6?<text x={x} y={y} className="courtyard-label">OTEVŘENÉ ATRIUM</text>:layout&&<text data-map-label className="room-code" x={x} y={y} transform={layout.rotate?`rotate(-90 ${x} ${y})`:undefined} style={{fontSize:layout.fontSize}}>{layout.labels.map((text,i)=><tspan key={text} x={x} dy={i===0?-(layout.labels.length-1)*layout.fontSize*.625:layout.fontSize*1.25}>{text}</tspan>)}</text>}</g>})}
 {wcMarkers.map(m=><text key={m.id} data-wc-marker x={m.point[0]} y={m.point[1]} className="wc-marker" style={{fontSize:9/mapScale}}>WC</text>)}

 {parts.map((p,i)=><g key={i} className="route-drawing"><polyline points={p.points.map(p=>p.join(',')).join(' ')} fill="none" stroke="white" strokeWidth="7" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/><polyline data-route-line points={p.points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#007d9b" strokeWidth="3.5" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/><polyline points={p.points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#fef7bc" strokeWidth="1.1" vectorEffect="non-scaling-stroke" strokeDasharray="3 8" className="route-motion"/>{p.points.length>0&&<><circle cx={p.points[0][0]} cy={p.points[0][1]} r="6" fill="#007d9b" stroke="white" strokeWidth="2"/><circle cx={p.points[p.points.length-1][0]} cy={p.points[p.points.length-1][1]} r="6" fill="#007d9b" stroke="white" strokeWidth="2"/></>}</g>)}
 {rooms.filter(r=>r.floor===floor&&r.id!=='entry-main'&&(r.id===selected||r.id===route?.from.id||r.id===route?.to.id)).map(r=><g key={r.id+'-pin'} transform={`translate(${r.door[0]},${r.door[1]-14/mapScale}) scale(${1.55/mapScale})`} className="room-pin" filter="url(#pin-shadow)"><path d="M0 9L-4 3A7 7 0 1 1 4 3Z" fill={r.id===route?.from.id?'#202428':'#007d9b'} stroke="white" strokeWidth="1"/><text textAnchor="middle" y="0" fill="white" fontSize="6" fontWeight="700">{r.id===route?.from.id?'A':r.id===route?.to.id?'B':r.kind==='entrance'?'↥':'•'}</text></g>)}
 {connectorMarkers.map(c=>{const [dx,dy]=c.offset;const screenX=(c.point[0]-visibleBounds[0])*mapScale+dx;const screenY=(c.point[1]-visibleBounds[1])*mapScale+dy;const boxX=Math.max(4-screenX,Math.min(-74,mapSize.width-screenX-153));const boxY=screenY>68?-66:22;return <g key={c.id} className={'landmark-connector '+c.kind+(c.active?' is-route-transfer':'')} transform={`translate(${c.point[0]},${c.point[1]}) scale(${1/mapScale})`} role={c.active?'button':'img'} tabIndex={c.active?0:undefined} aria-label={c.active?`${c.name}: ${nextFloorText(c.nextFloor!)}`:c.name} data-transfer-floor={c.active?c.nextFloor!:undefined} onKeyDown={e=>{if(c.active&&(e.key==='Enter'||e.key===' ')){e.preventDefault();changeFloor(c.nextFloor!);}}}><title>{c.name}</title>{Math.hypot(dx,dy)>1&&<path className="landmark-leader" d={`M0 0L${dx} ${dy}`}/>}<g transform={`translate(${dx},${dy})`}><rect className="connector-outline" x="-13" y="-13" width="26" height="26" rx="8"/><rect className="connector-symbol" x="-10" y="-10" width="20" height="20" rx="6"/><g transform="translate(-7,-7)" color="white">{c.kind==='elevator'?<Elevator size={14}/>:<Stairs size={14}/>}</g></g>{c.active&&<g className="transfer-label" transform={`translate(${boxX+dx},${boxY+dy})`}><rect width="149" height="44" rx="9"/><text x="10" y="15">{nextFloorText(c.nextFloor!)}</text><text className="transfer-subtitle" x="10" y="31">{c.kind==='stairs'?'Po schodech':'Výtahem'} · {c.nextFloor!+1}. NP →</text></g>}</g>})}
 {floor===0&&!entryOutside&&<g data-room-id="entry-main" className="main-entrance-marker" transform={`translate(${entry.point[0]},${entry.point[1]}) scale(${1/mapScale})`} role="button" tabIndex={0} aria-label="Hlavní vchod" onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectRoom(entry);}}}><path className="entrance-arrow-halo" d="M0 0L-10 12H-4V29H4V12H10Z"/><path className="entrance-arrow" d="M0 0L-10 12H-4V29H4V12H10Z"/><rect x="-69" y="34" width="122" height="28" rx="8"/><g transform="translate(-57,40)" color="white"><DoorOpen size={16}/></g><text x="-33" y="52">Hlavní vchod</text></g>}
 </svg>
 {entryOutside&&<button className="entry-locator" onClick={()=>selectRoom(entry)}><ArrowLeft size={17} style={{transform:'rotate(90deg)'}}/> Hlavní vchod</button>}
 <div className="map-tools"><button aria-label="Přiblížit mapu" onClick={()=>changeZoom(zoom*1.35)} disabled={zoom>=5}><Plus size={20}/></button><button aria-label="Oddálit mapu" onClick={()=>changeZoom(zoom/1.35)} disabled={zoom<=1}><Minus size={20}/></button><button aria-label="Zobrazit celé podlaží" onClick={fit}><LocateFixed size={20}/></button></div>
 <div className="map-legend"><span><i className="legend-room"/>Místnosti</span><span><i className="legend-office"/>WC</span><span><i className="legend-outside"/>Venku</span></div>
 {route&&<div className="floor-route-card" aria-live="polite"><div><span className="eyebrow">TRASA · {partIndex<0?'MIMO ZVOLENÉ PODLAŽÍ':`KROK ${partIndex+1} Z ${route.parts.length}`}</span><strong>{partIndex<0?'Přejdi na podlaží trasy':route.parts[partIndex].transition?nextFloorText(route.parts[partIndex].transition!.floor):'Cíl: '+route.to.label}</strong></div>{partIndex<0?<button aria-label="Ukázat začátek trasy" onClick={()=>changeFloor(route.parts[0].floor)}><ArrowRight size={19}/></button>:<div className="floor-route-actions"><button aria-label="Předchozí podlaží trasy" disabled={partIndex<=0} onClick={()=>changeFloor(route.parts[partIndex-1].floor)}><ArrowLeft size={18}/></button><button aria-label="Další podlaží trasy" disabled={partIndex>=route.parts.length-1} onClick={()=>changeFloor(route.parts[partIndex+1].floor)}><ArrowRight size={18}/></button></div>}</div>}
 <div className="map-source">Schéma FAI · U5 · {Math.round(zoom*100)} %</div>
 </section></div>
 <Dialog open={info} onOpenChange={setInfo}><DialogContent className="info-card" showCloseButton={false} aria-describedby={undefined}><button className="plain-button info-close" aria-label="Zavřít informace o mapě" onClick={()=>setInfo(false)}><X size={22}/></button><span className="eyebrow">FAI · MAPA U5</span><DialogTitle>Najdi svou cestu</DialogTitle><p>Vyhledej číslo místnosti nebo klepni přímo do mapy. Tlačítkem Odtud nastavíš začátek, tlačítkem Navigovat sem cíl.</p><p>1. NP je přízemí. Trasu mezi patry sleduj pomocí šipek nad mapou. Tlačítkem Upravit změníš začátek, cíl nebo způsob přesunu.</p><p>Spodní panel stáhneš dolů za úchyt nebo šipkou. Zůstane jen lišta pro hledání a navigaci. Tažením nahoru panel znovu otevřeš.</p><p>Mapu posouvej a přibližuj dvěma prsty. Popisky menších místností se objeví po přiblížení. Tlačítko zaměření znovu zobrazí celé podlaží.</p><p>WC jsou označené modře, hlavní vchod zelenou šipkou. Výrazná značka schodů nebo výtahu ukazuje další krok trasy; klepnutím přejdeš na následující podlaží. Zelené šrafování označuje venkovní plochy.</p><p className="info-links"><a href="https://vizual.utb.cz/index.php?p=fai" target="_blank" rel="noreferrer">Vizuální identita FAI ↗</a><a href="https://www.utb.cz/" target="_blank" rel="noreferrer">Univerzita Tomáše Bati ↗</a></p><button className="primary-button" onClick={()=>setInfo(false)}>Zpět na mapu</button></DialogContent></Dialog>
 </main>;
}
